controller_list:
  - name: fake_panda_arm_1_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  - name: fake_panda_arm_2_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
  - name: fake_panda_arm_3_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_3_joint1
      - panda_3_joint2
      - panda_3_joint3
      - panda_3_joint4
      - panda_3_joint5
      - panda_3_joint6
      - panda_3_joint7
  - name: fake_panda_arm_4_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_4_joint1
      - panda_4_joint2
      - panda_4_joint3
      - panda_4_joint4
      - panda_4_joint5
      - panda_4_joint6
      - panda_4_joint7
  - name: fake_hand_1_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_1_finger_joint1
      - panda_1_finger_joint2
  - name: fake_hand_2_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_2_finger_joint1
      - panda_2_finger_joint2
  - name: fake_hand_3_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_3_finger_joint1
      - panda_3_finger_joint2
  - name: fake_hand_4_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_4_finger_joint1
      - panda_4_finger_joint2
initial:  # Define initial robot poses per group
  - group: hand_1
    pose: open
  - group: hand_2
    pose: open
  - group: hand_3
    pose: open
  - group: hand_4
    pose: open