controller_list:
  - name: panda_1_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  - name: panda_2_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
  - name: panda_3_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_3_joint1
      - panda_3_joint2
      - panda_3_joint3
      - panda_3_joint4
      - panda_3_joint5
      - panda_3_joint6
      - panda_3_joint7
  - name: panda_4_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_4_joint1
      - panda_4_joint2
      - panda_4_joint3
      - panda_4_joint4
      - panda_4_joint5
      - panda_4_joint6
      - panda_4_joint7
  - name: hand_1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_1_finger_joint1
      - panda_1_finger_joint2
  - name: hand_2_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_2_finger_joint1
      - panda_2_finger_joint2
  - name: hand_3_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_3_finger_joint1
      - panda_3_finger_joint2
  - name: hand_4_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_4_finger_joint1
      - panda_4_finger_joint2
