right_arm_controller:
  type: "astronaut_controllers/ArucoTrajectoryController"
  end_effector_link: "gripper_right_base_link"
  base_link: "dummy_base_link"
  joints:
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint

  trajectory_duration: 9.0
  goal_tolerance: 0.015
  # kp_value: 1000.0
  # kv_value: 0.1
  kp_value: 300.0
  kv_value: 0.1
  
